// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/layout-options/LayoutA.tsx": () => import("../components/mockups/layout-options/LayoutA.tsx"),
  "./components/mockups/layout-options/LayoutB.tsx": () => import("../components/mockups/layout-options/LayoutB.tsx"),
  "./components/mockups/layout-options/LayoutC.tsx": () => import("../components/mockups/layout-options/LayoutC.tsx")
};
